//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poolio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionFailureMessage
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FailureMessage { get; set; }
    }
}
